# Generated by Django 3.1.3 on 2021-03-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210228_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='endDate',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('open', 'Open'), ('choice', 'Choice')], max_length=10),
        ),
    ]
