# Generated by Django 3.1.3 on 2021-10-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('value', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.user')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='submission',
        ),
        migrations.RemoveField(
            model_name='submittedanswer',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='survey',
            name='createdBy',
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
        migrations.DeleteModel(
            name='SubmittedAnswer',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
    ]
