# Generated by Django 3.1.3 on 2021-10-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20211010_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='type',
            field=models.CharField(choices=[('G', 'Glucose'), ('H', 'Heartbeat'), ('I', 'Insulin')], max_length=1),
        ),
    ]
